server:
  port: 8040
spring:
  data:
    mongodb:
      username: mongo
      password: mongo1234
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.poojithairosha.common.notification.dto.OrderConfirmation,paymentConfirmation:com.poojithairosha.common.notification.dto.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: admin
    password: 1234
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
